Add missing cstdint includes (#263).
Newer versions of GCC have become more strict about import of
known-size number types.

Currently, compiling IKOS leads to errors similar to the following:
In file included from /<<PKGBUILDDIR>>/core/include/ikos/core/domain/machine_int/abstract_domain.hpp:47,
                 from /<<PKGBUILDDIR>>/core/include/ikos/core/domain/machine_int/interval.hpp:46,
                 from /<<PKGBUILDDIR>>/analyzer/src/analysis/pointer/pointer.cpp:48:
/<<PKGBUILDDIR>>/core/include/ikos/core/domain/machine_int/operator.hpp:97:24: error: ‘uint64_t’ has not been declared
   97 |                        uint64_t result_bit_width,
      |                        ^~~~~~~~

This commits adds cstdint to the list of includes wherever a numerical
type with a known or fixed size is used.